ÖRNEK-2: EVDE ÇAY DEMLEME İŞLEMİ

1. BAŞLA
2. MUTFAĞA GİT
3. ÇAYDANLIĞI AL
4. ÇAYDANLIĞA SU KOY
5. ÇAY VARMI KONTROL ET EVET İSE 11 E GİT HAYIR İSE 6 YA GİT
6. HAZIRLAN
7. DIŞARI ÇIK
8. BAKKALA GİT
9. ÇAY AL
10. EVE GEL
11. ÇAYDANLIĞI OCAĞA KOY
12. ÇANDANLIK KAYNADI MI ? (KARAR MEKANİZMASI)
13. 7 EVET İSE 9. A GİT 7 HAYIR İSE BEKLE VE 7 Yİ KONTROL ET
14. DEMLİĞE ÇAY KOY
15. DEMLENDİ Mİ ? (EVET/HAYIR)
16. EĞER 10 EVET İSE 12 YE GİT HAYIR İSE 10 A GİT
17. SERVİS YAP
18. BİTİR


 ---- Ödev
## 1. Evde Çay yoksa.
## 2. Bakkal KAPALIYSA
## 3. Sular kesikse