ÖRNEK-2: EVDE ÇAY DEMLEME İŞLEMİ

1. BAŞLA
2. MUTFAĞA GİT
3. ÇAYDANLIĞI AL
4. ÇAYDANLIĞA SU KOY
5. SU VARMI KONTROL ET VAR İSE 9 A GİT YOK İSE 6 YA GİT
6. SUCUYU ARA
7. DAMACANA SİPARİŞİ VER
8. DAMACANAYI AL
9. OCAĞA SU KOY
10. ÇAYDANLIĞI OCAĞA KOY
11. ÇANDANLIK KAYNADI MI ? (KARAR MEKANİZMASI)
12. 7 EVET İSE 9. A GİT 7 HAYIR İSE BEKLE VE 7 Yİ KONTROL ET
13. DEMLİĞE ÇAY KOY
14. DEMLENDİ Mİ ? (EVET/HAYIR)
15. EĞER 10 EVET İSE 12 YE GİT HAYIR İSE 10 A GİT
16. SERVİS YAP
17. BİTİR


 ---- Ödev
## 1. Evde Çay yoksa.
## 2. Bakkal KAPALIYSA
## 3. Sular kesikse